import React from 'react'
import {
  ExperiencesAndTechnologiesBody,
  ExperiencesAndTechnologiesContainer
} from './ExperiencesAndTechnologies.elements'

const ExperiencesAndTechnologies: React.FC = () => {
  return (
    <ExperiencesAndTechnologiesBody>
      <ExperiencesAndTechnologiesContainer>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
        <h1>alo</h1>
      </ExperiencesAndTechnologiesContainer>
    </ExperiencesAndTechnologiesBody>
  )
}

export default ExperiencesAndTechnologies
